branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '12'
- '14'
before_install:
- mkdir cvc4/
- wget https://almond-static.stanford.edu/test-data/cvc4-1.6-x86_64-linux-opt -O cvc4/cvc4
- chmod +x cvc4/cvc4
- export PATH="`pwd`/cvc4:$PATH"
script:
- npm run lint
- npm run doc
- TZ="America/Los_Angeles" npm run test
after_success: npm run coverage
env:
  global:
  - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
  slack:
    secure: otIAjzXOCyKKXjeZ6azjxmfjVK5v9ziFuADWTQdgRlJUTNxu2YdJ8GX6ukWXxNAtR7v1cZxihZZi30y+dsmV6cocJqiZCLHwTDKTHHCzKzBjRq5OzfA6pfsyWqT3xGvuCM1v+U6BPLUQI56+jeUeb9pmJOwl8ac5CDXHi9StAu8B4XKNF/kGldLcsPGfFomVPGj5PzsZnp4phIDYc5UjPleRR+N9df+nAZaMRCR/hIRLtrsYRWuOeIAX9q+xovsx2ccrHBlsegu0ToTqFEZFIBXpHFGv9bDqc0kuizNTGM+d+1IPX4TYNurx9Ksbauao0DRuGD+yvPtbD+V8P9Jw+uslTam4D6WgLDfT1Jjk4wbN3OtKssYFmiwtLUGO/Up113MO5kNK1wpQRtRnDu59Rg0bOrpkdkB1t+SQ9KvJbYyRhu+42zw3qgSM29RRAuNIbHb7L4PZILzOieau8uDoQIOYWbYV47weK4/1/0zhQoF37+4TEqmkPI3jTcypgCUrqwdtuqOnD/EkoZVcg2EtttB/VahXmQO9cDZ0AX3GuVao7WFldrXKM8j+RPV6xaCj/RYO/6XZEkrgPFTF3rogCaw898VZ1AZvQqFgIcDyWsWpc9bzMVLDWHg4YMyTOQith/qLNeG3/EXPjofO3FmpqfaF3YuBjzD1SKEqgoa0Az8=
deploy:
- provider: npm
  email: gcampagn@cs.stanford.edu
  skip_cleanup: true
  api_key:
    secure: gc/zEzNZbLBtOXZJyezUqL+ht7JHQi+zIDYho4VKzc8U/8WZDwXYPmN5Qw6UO6vMGVETEcYy+nAdqE9TFutDtod7Ov6dk+IxSMFNUKiGQLASHhKyWylkaF8V9xao2Sso7MfYl9uMqfm1UTJHeWzJneY9eJc4r9W6T20w7YatTfjGuCtsSfRDtlsPKdyGoGno8BejfvGC05rUQpNegP6X7jkUJ1Hn/r5z6ZEVlQSfBucCCLQUyzB2NLXkFhPzYhaLPko+98qx5rIPbE2eyJU2TDusNpViV20aeVt7gI4O47gu49tpxoqoRpv8CY05eljGekVyi9K062KSLZnd0Td2GsY9y1vpu0PMPzNirCxY61cNrYoO8IHFHMnnejiTmTxq2oGrrNRQHK4t7CdOK7MmlxAH+Q5+DPGb5RE1ZGVeHjaLKc5jpLfAdp3cRUtkywR/wrPNF+eYFPdXeSCnfVcBfxjQFK0avT+a2jYTCfy7GCk+FZgaAcFlflr8pzXlLJsGM8cN/ld5X2FmMKAFpT1uZbV+VjFT1snwuRxOW9WJgDHeXH1fs8ufAeEyyleFt7rxsOyroEnASFNkSjJNQHxeaoNxQM8+LAVnOCjtrASlYq2a42251coSaBcHs6uTo6kcuK9JAxNIsQ4tHxcrQlV5smRz9ET8qp9w7IIJwTdMRDc=
  on:
    tags: true
    repo: stanford-oval/thingtalk
- provider: s3
  bucket: "geniehai-public"
  region: us-west-2
  skip_cleanup: true
  access_key_id:
    secure: "eDD9LlD+fvV5yya4NEyqqO01V1+7TMIoXeska72eJwIIkjhwI3AE8GeCMO690fpa7S25dQNhz40CK9+ZNt/t9lLmdha7sAn3q5DP05l4aPb0zH6pST/j8Wj+zbJVvY95rwrMEH++fuTlofMDhnard5xzMyMzG7j2OCivfrIdoAcQD0Kwb3GiEDvcm9qXiqyKXo0mRPlAnq00x87wLhHZZAWxcR4WgEmnO5aep+A5EsjB8RqNgPKb9zXNavQfMP5MXvrRUV9YYiEAcPwcQqLVkQ0WNTUsGqdCBV8ttNnUsy2m2KNuLQ4zWaRPN65Jh2JEl4lCaPvQdkw+cCdRnrrbIlr5sQzgyZNfpnb1ZWJUiEG1srjslGGW82El4xJww6bma7ygNWGvK1+y2AIvpKr+KbS2r88U4GTTrOZgby5ms8dHw1wIcOYLNtCvUAil4wPcNpQWsGx0oAdbjMewY86DbhJwLgs56na6LjSuS+ORkHFg55TByagoywMC2Hv8PRW4j9wZALdRJx7LQmGBPo2hGvtUVeokiWxrVJzpGYrhQ6gq7+McIvQHvqxduXlwEroMqaa5IQkY4/6aI1Reeo6hAwXFrAS8F92LyWmeZsfHvruAm5IoxB4n5QUXaNJzzRZziCkWZkiiDAz5s7NlUjzUiQt+J3f2melWjPXkKrD2Xls="
  secret_access_key:
    secure: "Swu/2VhR2gsrrPBETBxJZlwiCk6Ch+NULDDP/OLZrsKo+ryLbxvBrTWd7homtLVP3hPG+Idq6Gs+XXr7ghXZ/cG4Am4poLVfFobZgq/CM5MlgE25ZiqnlmmfjnezL1EPBTw9EN4R6tzeijyp6AbWcw6UDR6yBHm1RBd8y7QFXw5gSss31GuSlgdPcTaNgwxmqR6HcVnzjPamPrmIBx6BZoq4iLyBxII7v0LwXcDpFLppnMHbFz2Agz8lfjit87qffjd+cQHyuIC7wHNja+FdXLUKOwKGaEFqAHLbuUr1FgY8rCZcRimk43uFSILHOu39fURBwv09wWjMXAuoCMs36TsfhdWEUgcE0wn8U4qsLWAWNN+arstmZtDyhjyR3roKeAoWRsYDWjwf3tusNC2bbbYS2y0FX+QNZqKDLyQ1tuiS69pQEwMaSSNZUa9wvz7sHTvCRq89vqPNg4EVUE1obdKwAoR03PgP0CX1qJuz4w+FvTMJ+1PE2aLlDgKbDWehxMKtKjZgfNNJ7HETky7ESldbOwVczg6a1vmpopvUvTdBh9lTWw6AYnYS1GFkdl7QTVN/16fOG9zXbAj8sQPnE+aFxADMzhyXX1tm+dQw9NzyKDVK6flUojcflM79Xxjnt0XLNsazh/Hpk0YckAqjnJ9VpJ3RoLH+kPFwVjEZA+8="
  localdir: doc
  upload-dir: jsdoc/thingtalk/latest
  on:
    branch: master
    repo: stanford-oval/thingtalk
